services:
  express-ts-prisma:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - APP_PORT=3000
      - APP_NAME=express-ts-prisma
      - APP_LOG_LEVEL=debug
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/express-ts-prisma?schema=public
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY="mysupersecret"
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=express-ts-prisma

  redis:
    image: redis
    ports:
      - 6380:6379
